### ISSUE TITLE
Webpage is not auto-reloading

### ISSUE THREAD

**Issue by amexn-me** [spalt08/go-live-reload#2]
Hey,
This is a great repo as it exclusively take care of the task without considering any third party packages.
Here's something bugging me. The webpage isn't reloading after server is restarted. Once we manually refresh the page, we can see the changes. It's like that or is there something that I need to be taking care of?

Edit: Typo

**Comment by spalt08** [comment]
Hi!
This setup will only rebuild and reload golang binary for every file save. Refreshing the page is not related here
